name: iControlU
main: icontrolu\iControlU
version: 1.4.0
author: Falkirks
api: [3.0.0, 4.0.0]
load: POSTWORLD
commands:
 icu:
  permission: icu.use
  description: Control other players
  usage: /icu (c)ontrol <player> | (s)top
permissions:
 icu:
  default: op
  children:
   icu.use:
    default: op
    description: Main iControlU perm
   icu.control:
    default: op
    description: Can control others
   icu.stop:
    default: op
    description: Stop controlling
   icu.exempt:
    default: op
    description: Exempt from being controlled
